# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between Ethereum and Binance Smart Chain and Lumia
description: Hyperlane Warp Route artifacts
timestamp: '2024-10-18T14:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    ethereum:
      protocolType: ethereum
      type: collateral
      hypAddress: '0xA4e45cB601d43818518FB6023b8070d2564b935f'
      tokenAddress: '0x5fD13359Ba15A84B76f7F87568309040176167cd'
      name: Amphor Restaked ETH
      symbol: AMPHRETH
      decimals: 18
    zircuit:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0xCE8260c1b5cF2fAD15bb4B6542716b050Fdf35c9'
      name: Amphor Restaked ETH
      symbol: AMPHRETH
      decimals: 18
